### ISSUE TITLE
Loading splash gif not working

### ISSUE THREAD

**Issue by JordieG00n** [araten10/EdgewarePlusPlus#103]
How do you add a gif for the loading splash? Nothing I do seems to work. 

In the example pack, there's the gif named 'loading_splash' but this doesnt work and it just uses the default. 

And when trying to change the default, it only accepts PNG and not gif. 

Running latest python and edgeware. Is there a way to get this to work? 

:)

**Comment by LewdDevelopment** [comment]
There was a bug with using startup splashes from packs, it's fixed with 2168fd4. At the moment there are no plans for different file types for the default assets, but this is something that could be added in the future.
