### ISSUE TITLE
Bug: Discord status keeps resetting back to 0:00 played

### ISSUE THREAD

**Issue by CountVirgo** [araten10/EdgewarePlusPlus#109]
I noticed recently when  running EdgewarePlusPlus my discord status keeps resetting back to 0:00 played.

Video example showing this:

https://github.com/user-attachments/assets/2d98b58f-186c-48da-a1d7-74551db47431

This happens repeatedly every few seconds - EdgewarePlusPlus is still running just fine when the reset happens so I have no idea what's triggering it. I've confirmed the same behaviour on both Windows and Linux.

No errors etc. are registered in any of the logs, so I'm not sure what else I can provide to help debug this if you're not able to reproduce.

It's not a pack issue, as the same thing happens when using Edgeware++ Test Pack V2.

Tested on Win 10 64bit 22H2 + Ubuntu 24.04.1, Python 3.12.7 on both.

config.json attached in the case it's something to do with that:
[config.json](https://github.com/user-attachments/files/17467228/config.json)

**Comment by LewdDevelopment** [comment]
This looks like a bug that may have existed since the original Edgeware. I pushed a potential fix in 4f79d66, but I don't personally use Discord so I can't test it. Let me know if it works!

**Comment by CountVirgo** [comment]
That looks to have fixed it, thank you :) before now it had never gone past around 15-20 seconds without a reset:
![PEW](https://github.com/user-attachments/assets/1ab4ade6-a902-4557-a211-5390776a34a9)

**Comment by CountVirgo** [comment]
That looks to have fixed it, thank you :) before now it had never gone past around 15-20 seconds without a reset:
![PEW](https://github.com/user-attachments/assets/1ab4ade6-a902-4557-a211-5390776a34a9)
