### ISSUE TITLE
Setup not finding requirements file/not working

### ISSUE THREAD

**Issue by smorger32** [araten10/EdgewarePlusPlus#115]
I reinstalled edgeware to try and fix a bug because it wouldn't run and upon running the setup, the terminal closed and nothing happened, it also doesn't make the shortcuts. I re-ran it as an administrator and got this output: 

![issue](https://github.com/user-attachments/assets/50343391-47db-43e2-8501-7f164949b2b6)

It apparently can't find the requirement file despite it being in the edgeware folder. 

![issue 2](https://github.com/user-attachments/assets/c7328c53-a122-445c-a2ee-0354ea05f2ee)

Additional context if necessary: before reinstalling when I'd open up the config (the terminal would also open for some reason when it hadn't previously) and try to run on save and exit, it would say that it couldn't find edgeware.pyw in the terminal.

**Comment by theyahoogirl** [comment]
"Run as administrator" changes the starting folder. However, you can run the .bat file from the terminal in Windows in the right place by right-clicking the folder and selecting "Run from Terminal", then putting ".\EdgewareSetup.bat" (without "") and pressing enter. This shows you what is going on in the window that closes automatically.

![image](https://github.com/user-attachments/assets/448a6bdb-4628-4e39-a31a-9ff42548a281)

If you then run into the problem where it can't find shortcut/shortcuts, try opening the file "EdgewareSetup.bat" in Notepad by right-clicking on the file and choosing "Edit in Notepad", search (Ctrl + F) for "shortcut" in the Notepad window and change both goto shortcut and :shortcut to the shortcut folder, i.e. src in your screenshot, and save your changes.

![image](https://github.com/user-attachments/assets/6e9f7ac3-5382-4cc8-bfda-6d7f762ce931)

Then, run the EdgewareSetup file normally (i.e. not in Terminal or as administrator), and it should work. If it doesn't, post what errors you get here and I'll try and troubleshoot further :)

**Comment by LewdDevelopment** [comment]
> "Run as administrator" changes the starting folder.

Ah OK, that explains the `requirements.txt` issue. In that case, this should be fixed in d472970.
