### ISSUE TITLE
Cant get it to do anything

### ISSUE THREAD

**Issue by Krystal6666** [araten10/EdgewarePlusPlus#117]
Hi, Installed latest version of ++
Installed python 12.x
Run application and id does nothing but give me normal wall paper.
After doing some research i tried running : "pip install pillow==9.1.1"
and got the response : "Pillow 9.1.1 does not support Python 3.12 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows."
In the trouble shooting window i get :
The media treeview nodes couldn't finish their checking setup!
The captions treeview nodes couldn't finish their checking setup!
The prompt treeview nodes couldn't finish their checking setup!
The web treeview nodes couldn't finish their checking setup!
And ideas?

**Comment by Wombatant1** [comment]
Did you run setup batch file? There is one in the main folder. If you did, make sure you're using a pack that is loaded correctly - you should have your resources put directly into ./resources; some packages are extracted wrong, eg: ./resources/New folder/[files]

**Comment by JohnWest24** [comment]
Did a fresh install of Python and Edgeware. Pack Info menu is showing the content counts of the imported pack (hypno from the original Edgeware page). I'm also finding that the only thing changing is the wallpaper, and I'm getting the same errors.

[logs.zip](https://github.com/user-attachments/files/17990060/logs.zip)

**Comment by Wombatant1** [comment]
I'd recommend redownloading edgewate++, cause in logs there's version 9.3, while currently we're at v13 I believe. I'd also try running a default testing pack (it's linked in "Packs" section of README.md
