### ISSUE TITLE
Keybind for Panic mode does not function when pressed.

### ISSUE THREAD

**Issue by AnonPupp** [araten10/EdgewarePlusPlus#118]
I am running Edgeware on windows 10 with 8GB ram. (HP BRAND LAPTOP)
I go to configure and add a key bind to the panic button and it seems to work fine, but when I press the actual key while having the program enabled it does not enable panic. Any and all help is appreciated!

**Comment by Wombatant1** [comment]
If you're using it with button less popup closing, you need to click and hold popup while clicking panic keybind
Check whether panic is enabled - there's checkbox to disable toolbar and keybind panic
