### ISSUE TITLE
Desktop Shortcuts Don't Appear

### ISSUE THREAD

**Issue by dinhgp2** [araten10/EdgewarePlusPlus#37]
After a fresh install today (few minutes ago) there is no popup icon for config, panic and start.

**Comment by LewdDevelopment** [comment]
Could you provide logs from when you start Edgeware?

**Comment by dinhgp2** [comment]
[Wed_Apr__3_21-08-32_2024-ew_start.txt](https://github.com/araten10/EdgewarePlusPlus/files/14858108/Wed_Apr__3_21-08-32_2024-ew_start.txt)
[Wed_Apr__3_21-08-32_2024-ew_start.txt](https://github.com/araten10/EdgewarePlusPlus/files/14858114/Wed_Apr__3_21-08-32_2024-ew_start.txt)

**Comment by LewdDevelopment** [comment]
Thanks! I pushed a fix for the warnings in the logs, but I don't use Windows so I can't test whether desktop shortcuts work now.

**Comment by dinhgp2** [comment]
That solved it, thank you
