### ISSUE TITLE
Launch on startup doesn't function

### ISSUE THREAD

**Issue by dinhgp2** [araten10/EdgewarePlusPlus#38]
Launch on startup doesn't work, have to start the program manually even after restarting with the option selected

**Comment by LewdDevelopment** [comment]
Could you send logs of when you save and exit the config window after enabling launch on startup? I'll see what I can do.

The logs may also contain your PC username so you can check the file and censor it first if you want to. I can also try to add a precaution against this.

**Comment by dinhgp2** [comment]
[Fri_Apr__5_13-22-59_2024-dbg.txt](https://github.com/araten10/EdgewarePlusPlus/files/14884738/Fri_Apr__5_13-22-59_2024-dbg.txt)

**Comment by dinhgp2** [comment]
That did it, thanks again

**Comment by Heizou111** [comment]
I'm still having this issue. Another issue is that when startup is toggled, I am unable to save and close the config window. I can save and close with timer mode toggled but it still doesn't startup.
