### ISSUE TITLE
wallpaper scaling

### ISSUE THREAD

**Issue by Wombatant1** [araten10/EdgewarePlusPlus#42]
Hey, is it possible to add a setting that could force wallpaper scaling? I don't know if thats default windows setting but i had porblem with wallpapers ending up as a poorly cropped photo or a tiny one in the middle of black screen

**Comment by araten10** [comment]
I feel similarly, I don't necessarily want to create a situation where somebody has to go into their settings menu to revert things back to how they were before edgeware in the case of edgeware crashing or unexpectedly being closed without using panic, in addition to the issues LewdDevelopment already brought up. If I end up making a detailed tutorial or reference manual I might add a mention to this if it would help clear up confusion, however
