### ISSUE TITLE
Attempting to use full folder wired to an older version of Edgeware.

### ISSUE THREAD

**Issue by dinhgp2** [araten10/EdgewarePlusPlus#45]
I'm trying to use these packs created by a user called
![Screenshot 2024-04-24 165330](https://github.com/araten10/EdgewarePlusPlus/assets/165954805/24050858-7d52-4130-8820-3fbdf82b6dc2)
 Lillyvirus. I can't edit the packs as they're wired to this = https://raw.githubusercontent.com/PetitTournesol/Edgeware/main/EdgeWare/configDefault.dat

I tried to recode the line to the raw settings of this but cannot save the change. Any ideas? 
Thanks.

**Comment by catzillaowo** [comment]
if you go to the resource file you can pull the pack items, lilyvirus has her pack built into edgeware with a bit of custom script.

**Comment by araten10** [comment]
I have heard mention of this pack before- catzilla has it right, I believe lilyvirus has custom scripts built into her version of edgeware. As for if they're malicious or not, I can't personally verify- however by extracting the resources as mentioned you should be able to use them in standard edgeware++.
