### ISSUE TITLE
popup error

### ISSUE THREAD

**Issue by gobind915** [araten10/EdgewarePlusPlus#47]
i downloaded anaconda to work on a project and installing it with all of its python resources messed up edgeware. Presumably its because I downloaded 3.12, and the popup code breaks down for that
(Traceback (most recent call last):
  File "C:\Users\------\Downloads\EdgewarePlusPlus-main1\EdgewarePlusPlus-main\EdgeWare\subprocesses\popup.pyw", line 73, in <module>
    MOOD_ID = SYS_ARGS[0].strip("-")
IndexError: list index out of range is the error)
I tried using python 3.10 but that one doesn't seem to work at all, nothing shows up. Dont use python to make programs like this myself so I don't understand what exactly went wrong when I downloaded anaconda, and I don't have the context to figure out this error

**Comment by gobind915** [comment]
i take it back, even when i use versions where the opup file works, using the start file still doesnt bring up the popups, it just changes my wallpaper

**Comment by TiffyPornwhore** [comment]
I think the latest update to Edgeware just broke it. It hasn't worked for me either
