### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by TiffyPornwhore** [araten10/EdgewarePlusPlus#49]
Downloaded the new update and it still doesn't work. These are the error messages now:

The media treeview nodes couldn't finish their checking setup!
The captions treeview nodes couldn't finish their checking setup!
The prompt treeview nodes couldn't finish their checking setup!
The web.json treeview couldn't load properly!
The web treeview nodes couldn't finish their checking setup!

What's going on???

**Comment by araten10** [comment]
Does it not work entirely, or are those messages just coming up in the error view? They aren't necessarily things that would stop the entire program from working, just indicators that certain ++ features aren't loaded in properly

**Comment by TiffyPornwhore** [comment]
Straight up not functioning at all. It changes the wallpaper but doesn't have any popups or anything.

**Comment by araten10** [comment]
Is it possible to post logs of the program not running from your logs folder? does running start or config in the debug file give errors? can you post the contents of your config file?

**Comment by TiffyPornwhore** [comment]
This is what I found in the logs from my last attempt at running it

INFO:Started start logging successfully.
INFO:args: []
INFO:loading config...
INFO:read in settings from default.json
INFO:read in settings from config.cfg
INFO:mood id: 4404wsdix
INFO:found prompt.json
INFO:found web.json
INFO:image resources found
INFO:video resources found
INFO:audio resources found
INFO:started loading flair
INFO:using lanczos for loading flair
INFO:set user wallpaper to default wallpaper.png
INFO:entered main function
DEBUG:Importing BlpImagePlugin
DEBUG:Importing BmpImagePlugin
DEBUG:Importing BufrStubImagePlugin
DEBUG:Importing CurImagePlugin
DEBUG:Importing DcxImagePlugin
DEBUG:Importing DdsImagePlugin
DEBUG:Importing EpsImagePlugin
DEBUG:Importing FitsImagePlugin
DEBUG:Importing FitsStubImagePlugin
DEBUG:Importing FliImagePlugin
DEBUG:Importing FpxImagePlugin
DEBUG:Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG:Importing FtexImagePlugin
DEBUG:Importing GbrImagePlugin
DEBUG:Importing GifImagePlugin
DEBUG:Importing GribStubImagePlugin
DEBUG:Importing Hdf5StubImagePlugin
DEBUG:Importing IcnsImagePlugin
DEBUG:Importing IcoImagePlugin
DEBUG:Importing ImImagePlugin
DEBUG:Importing ImtImagePlugin
DEBUG:Importing IptcImagePlugin
DEBUG:Importing JpegImagePlugin
DEBUG:Importing Jpeg2KImagePlugin
DEBUG:Importing McIdasImagePlugin
DEBUG:Importing MicImagePlugin
DEBUG:Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG:Importing MpegImagePlugin
DEBUG:Importing MpoImagePlugin
DEBUG:Importing MspImagePlugin
DEBUG:Importing PalmImagePlugin
DEBUG:Importing PcdImagePlugin
DEBUG:Importing PcxImagePlugin
DEBUG:Importing PdfImagePlugin
DEBUG:Importing PixarImagePlugin
DEBUG:Importing PngImagePlugin
DEBUG:Importing PpmImagePlugin
DEBUG:Importing PsdImagePlugin
DEBUG:Importing SgiImagePlugin
DEBUG:Importing SpiderImagePlugin
DEBUG:Importing SunImagePlugin
DEBUG:Importing TgaImagePlugin
DEBUG:Importing TiffImagePlugin
DEBUG:Importing WebPImagePlugin
DEBUG:Importing WmfImagePlugin
DEBUG:Importing XbmImagePlugin
DEBUG:Importing XpmImagePlugin
DEBUG:Importing XVThumbImagePlugin
INFO:starting annoyance loop

Hope to God I didn't somehow doxx myself with this lol

**Comment by LucySuby** [comment]
It seems that you are missing a module.
Open a terminal and write "python3 -m pip install olefile"

According to this issue on "Pillow" : https://github.com/python-pillow/Pillow/issues/4585, it seems that it's an optional dependency and thus is not automatically installed when installing "Pillow".
It should maybe be added as a requirement in the "requirement.txt" file ?

**Comment by LewdDevelopment** [comment]
`olefile` is not necessary for Edgeware, the lines complaining about it show up to the logs even when everything works.

Are there any errors when you launch a popup from the debug script?

**Comment by TiffyPornwhore** [comment]
> python3 -m pip install olefile

It says "Python was not found". I thought maybe it was just not installed for somewhy so I downloaded the newest version and now it's not even opening the config window. Am I stupid?

**Comment by TiffyPornwhore** [comment]
> Are there any errors when you launch a popup from the debug script?

No idea how to do that, and even if I did the config window isn't opening anymore

**Comment by TiffyPornwhore** [comment]
Gave it a fresh re-install and the whole thing works. I swear I tried that before but whatever. Sorry for the waste of time
