### ISSUE TITLE
Can't open config

### ISSUE THREAD

**Issue by sconners8** [araten10/EdgewarePlusPlus#50]
I tried updating to the newest version and after running the setup bat, it doesn't show any errors or missing requirements and when I hit a button cmd briefly pops up with the config title but does not display any lines of code before it disappears. I can run the start and it seems to work, but I can't open the config

**Comment by araten10** [comment]
Do log files generate for the config window? (in the logs folder) Does running config with the debug script give any errors?

**Comment by eznametoremember** [comment]
Running from Sublime Text I get the following:

ImportError: cannot import name 'utils' from 'utils'

This is after having run the setup bat and reinstalled utils to be safe.

**Comment by sconners8** [comment]
When I run the config file on its own I get the same thing. A CMD window briefly pops up with no dialog and disappears. When I run the debug script, nothing pops up, no cmd window but I do get the loading icon on my mouse cursor. I'm unsure how to get the logs to generate. I have a few that seem to be generated as a result of running the start script but that is working fine. The program works fine aside from me not being able to launch the config and issues with vlc. It keeps crashing on launch but that's a separate issue

**Comment by N0N0Evil** [comment]
Have you tried updating python? I updated to 3.12.3 and it worked after rerunning the setup script. I think the setup script isn't working with older versions of python anymore.

https://www.python.org/downloads/

**Comment by sconners8** [comment]
I actually got fed up with my pc's boot times because I built it forever ago and just never moved windows over to an ssd so I just reinstalled windows to an ssd and then I had to reinstall basically everything but I think you are correct. I believe python itself was out of date.
