### ISSUE TITLE
Hibernate mode not working

### ISSUE THREAD

**Issue by ajasnam** [araten10/EdgewarePlusPlus#55]
Despite the fixes in issue #53, hibernate mode does not work for me whatever type is chosen, including original.

 When Edgeware++ is run, after selecting hibernate and saving, the splash screen comes up, closes and then nothing happens, whatever parameters were set.
  Additionally, if the skip hibernate time option is checked in the troubleshooting section, no tray icon appears when running in hibernate mode.

No hibernate related errors appear in the log files. The only log is the _Started in hibernate mode_ information log.

**Comment by AddictAnime** [comment]
Has there been any update into this lately? Whether you found any sort of fix for it that works well enough, or if we just need to wait for an update?

**Comment by donordirt** [comment]
Seems to be line 347 in start.pyw:
```
with open(Data.CORRUPTION_LEVEL, "r") as f:
    tracked_level = int(f.read())
```
I don't know how python handles files very well, so I don't know what the issue is. Commenting out the code and replacing it with ```tracked_level = 0``` works for me.

**Comment by princessGasmask** [comment]
> Seems to be line 347 in start.pyw:
> 
> ```
> with open(Data.CORRUPTION_LEVEL, "r") as f:
>     tracked_level = int(f.read())
> ```
> 
> I don't know how python handles files very well, so I don't know what the issue is. Commenting out the code and replacing it with `tracked_level = 0` works for me.

Which lines did you comment out? I'm having this same issue now
