### ISSUE TITLE
wasn't working 

### ISSUE THREAD

**Issue by klabawef** [araten10/EdgewarePlusPlus#57]
ive tried reinstalling and everything but nothing works, i checked the task manager to ensure something is running in the background, but there are nothing happening at al, even with the test pack where the config menu said no errors were detected

**Comment by araten10** [comment]
this is a delayed response but if you are still having issues feel free to contact me elsewhere or open another issue- unfortunately due to the massive amount of variances from setup to setup there isn't a clear path on what is going wrong on your install
