### ISSUE TITLE
Hibernate mode cannot create popups

### ISSUE THREAD

**Issue by donordirt** [araten10/EdgewarePlusPlus#58]
The hibernate mode loop's ```roll_for_initiative()``` calls don't send the corruption chance, and all hibernation modes fail when they attempt to create a popup.

This is separate from #55. Hibernation mode is cursed.

**Comment by spencershoe** [comment]
Same issue here on linux. no errors when ran in console, but the log says
`WARNING:failed to successfully run Glitch hibernate.
    Reason: roll_for_initiative() missing 1 required positional argument: 'corr_chance'`

**Comment by LewdDevelopment** [comment]
This should be fixed by #59, I was waiting for @araten10 to merge it but I suppose I can do that now.
