### ISSUE TITLE
Panic is broken in timer mode

### ISSUE THREAD

**Issue by LewdDevelopment** [araten10/EdgewarePlusPlus#6]
Panicking doesn't consistently work in timer mode, including tray panic not working at all.

**Comment by Wombatant1** [comment]
I would add that passwords work very inconsistently. While first run after setting timer mode and password runs right, I can use panic (as a hotkey) and terminate program with a password, any next time I run it (without restarting pc) doesn't allow me to terminate with password. I can only close it with panic.pyw, but it also doesn't work every time

**Comment by iLegendaryCrab** [comment]
I've found that in the panic.pyw file changing "if os.path.exists(Data.HID_TIME)" to "if os.path.exists(Data.PASS_HASH)" seems to fix the issue of panic not working, although sometimes hid_time.dat will not get deleted properly
