### ISSUE TITLE
[linux] all hibernate popups appear in same spot.

### ISSUE THREAD

**Issue by spencershoe** [araten10/EdgewarePlusPlus#61]
All popups open in the center of the screen and only on the monitor the mouse is on. I'm running arch linux, with the kde plasma desktop environment. Working on a temp fix will keep everyone posted.

**Comment by spencershoe** [comment]
also clicking anywhere on any popup seems to close it even if buttonless closing is off, and moving popups also don't work but those usecases are more niche.

**Comment by spencershoe** [comment]
Can anyone point me to the part of code where a popup's location is determined? i can't seem to find it...

**Comment by LewdDevelopment** [comment]
Lines 492-512 of `subprocesses/popup.pyw` are probably what you want.

**Comment by s-b-repo** [comment]
im also using linux would be nice if it worked on kde

**Comment by spencershoe** [comment]
for some reason adding `root.overrideredirect(True)` to just before the root geometry call makes it work. it also prevents you from moving the windows around using super+drag on plasma.

**Comment by LewdDevelopment** [comment]
`overrideredirect(True)` is used on Windows, but on Linux I replaced it with `attributes("-type", "splash")` because on GNOME, it was making it impossible to focus popups and thus use the panic hotkey as well as enter prompts. Do these still work as expected with `overrideredirect` on KDE? If so, this might need to be handled separately in different DEs.

**Comment by s-b-repo** [comment]
> `overrideredirect(True)` is used on Windows, but on Linux I replaced it with `attributes("-type", "splash")` because on GNOME, it was making it impossible to focus popups and thus use the panic hotkey as well as enter prompts. Do these still work as expected with `overrideredirect` on KDE? If so, this might need to be handled separately in different DEs.

try using xwayland so it work on wayland and on x11

**Comment by LewdDevelopment** [comment]
Should be fixed by da6fe35
