### ISSUE TITLE
How to run it on Linux?

### ISSUE THREAD

**Issue by Seiryu90** [araten10/EdgewarePlusPlus#62]
Hello,

I'm here because I wanted to run Edgeware++ on Linux, I got exited, but I couldn't run it because it doesn't recognize the file existing or directory to the file. Is there anyway to fix this and get to gooning?

From,
Seiryū

**Comment by Seiryu90** [comment]
Never Mind, had to download most of the requirements manually. But "vlc fails to load" keeps popping up on Terminal, and when I tried installing "pygobject", it doesn't work.

**Comment by LewdDevelopment** [comment]
The VLC warning should not be a problem unless you want to use the VLC mode to play videos, in which case you will have to install VLC separately first.

> when I tried installing "pygobject", it doesn't work.

What do you mean by this? Do you get any warnings or errors?

**Comment by Seiryu90** [comment]
Hello, I decided to switch to Arch Linux, and I'm having trouble to get it to work. I'm wondering if anyone in the community who knows Arch Linux stuff that are able to help me?

**Comment by s-b-repo** [comment]
i know arch linux

**Comment by s-b-repo** [comment]
i use arch linux everyday

**Comment by LewdDevelopment** [comment]
Closing this for now, but if you still have problems, feel free to open another issue.
