### ISSUE TITLE
Corruption Transitions "Timed" and "Popup" do not transition between levels

### ISSUE THREAD

**Issue by AddictAnime** [araten10/EdgewarePlusPlus#64]
Managed to get corruption to work for my own custom pack I'm working on, but when I was running it on Version 12, setting it to go up a level after 10-20 seconds (As a test) or after 15 popups would not work.

I toggled purity mode after to see if it was an issue with levels, but it did start at the last level like it should. I wondered if the Launches trigger would work, and sure enough the launches trigger works just fine for levelling up, but unfortunately this method doesn't really interest me.

I tried a corruption pack I knew already worked for these triggers, but alas this pack didn't work either. I went back to an older version I have (EdgeWare++ Version 11, specifically the Config Reorganize branch) and tested that pack to see it level up every 10 seconds just like I asked it to, which pinpoints the issue to being something with Version 12 I believe.

**Comment by araten10** [comment]
if you could potentially send me your pack/post the corruption file I might be able to see what's up- currently the main code is going through a major refactor so it might be a bug that is unsolved currently, but i'd like to at least test it and see what's going on!
