### ISSUE TITLE
using pip safely

### ISSUE THREAD

**Issue by s-b-repo** [araten10/EdgewarePlusPlus#70]
for arch and some systems pip can destroy your system it is reccomened to use venv

https://docs.python.org/3/library/venv.html

**Comment by s-b-repo** [comment]
sudo python -m venv /home/EdgewarePlusPlus-main

**Comment by s-b-repo** [comment]
mkdir projectA
 cd projectA
 python3.8 -m venv env

**Comment by s-b-repo** [comment]
https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/

**Comment by LewdDevelopment** [comment]
Arch doesn't let you use `pip install` outside a virtual environment without passing `--break-system-packages` and directs you to use a venv when you try, so I figured it would be fine not to mention it. Not very good reasoning, I know. Using a venv is indeed much better practice.

I intend to include some setup scripts for Linux which automatically create a venv for Edgeware and use it to run it.

**Comment by s-b-repo** [comment]
> Arch doesn't let you use `pip install` outside a virtual environment without passing `--break-system-packages` and directs you to use a venv when you try, so I figured it would be fine not to mention it. Not very good reasoning, I know. Using a venv is indeed much better practice.
> 
> I intend to include some setup scripts for Linux which automatically create a venv for Edgeware and use it to run it.

i once broke my whole system pip installing one thing on arch
