### ISSUE TITLE
suggestion for pack creator

### ISSUE THREAD

**Issue by s-b-repo** [araten10/EdgewarePlusPlus#72]
for pack creator can a multi folder layout be made for example one for videos all videos in that folder are used one for music and audio and on for like costum scripts and also pop up content to make it easier to make packs and also make multiable packs and seprate them via profiles

**Comment by araten10** [comment]
I am potentially looking into adding a separation between music and short audio files, but other than that I don't know if the packs will be split into more folders. Other than needing to rewrite a large chunk of mood code, this also would make them potentially incompatible with old versions of edgeware which I am trying to avoid.

**Comment by s-b-repo** [comment]
this would make it easy to switch between packs and bring more users and make it so more people gain intrest

**Comment by LewdDevelopment** [comment]
I think this feature doesn't offer any tangible benefits and would only increase complexity. I don't see how this is related to switching packs though? Did you mean to comment on #111?
