### ISSUE TITLE
No start.pyw in new version?

### ISSUE THREAD

**Issue by JennaStarlight** [araten10/EdgewarePlusPlus#83]
I might be a bit confused but does the new update not contain a start.pyw? I tried setting up some stuff and it just won't work. So am i dumb or is it missing?

**Comment by LewdDevelopment** [comment]
You use `edgeware.pyw` to launch the program now. Some of the instructions are outdated ATM, but they will be updated in the near future.

**Comment by JennaStarlight** [comment]
oh okii thank you :3, i guess it
