### ISSUE TITLE
Linux issues.

### ISSUE THREAD

**Issue by Garbanzo95** [araten10/EdgewarePlusPlus#85]
hello, i have compiled a list of issues on linux KDE plasma.

- popups appear only in center of screen.
- popups become invisible when clicked, and momentarily become visible when panic is activated. (only on x11)
- videos and some images are are now cropped instead of scaled.

**Comment by LewdDevelopment** [comment]
Should be fixed by da6fe35

**Comment by Garbanzo95** [comment]
THANKS!
