### ISSUE TITLE
Running Edgeware.pyw doesn't do anything

### ISSUE THREAD

**Issue by CurtainDude** [araten10/EdgewarePlusPlus#87]
Hi, I'm sure you get a lot of reports so sorry to give you another one.
I've been trying to update to the new edgeware plus plus but whenever I click "run on save & exit" or run edgeware.pyw, nothing happens. I've tried reinstalling, moving to a new file location, running different packs, but none of it is working.
I've attached the most recent logs.
Sorry if this causes any hassle
[Tue_Sep_24_15-57-08_2024-config.txt](https://github.com/user-attachments/files/17116601/Tue_Sep_24_15-57-08_2024-config.txt)
[Tue_Sep_24_15-58-07_2024-config.txt](https://github.com/user-attachments/files/17116602/Tue_Sep_24_15-58-07_2024-config.txt)

**Comment by LewdDevelopment** [comment]
Have you made sure you're using Python 3.12? Does running Edgeware through the debug script `edgeware/debug.py` give any output?

**Comment by CurtainDude** [comment]
> Have you made sure you're using Python 3.12? Does running Edgeware through the debug script `edgeware/debug.py` give any output?

Hi, so I am an idiot and didn't update my python. Thanks for telling me lol, it works now. Love all of the new features you have added, I haven't updated since a year ago and it's crazy how much has been added.
