### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by shez101** [araten10/EdgewarePlusPlus#90]
So when I set it up, I run the program. The loading screen launches, but nothing else pops up. I ran the debug program. Number 2 seems fine, but number 1 starts off like this:
Select number: 1
INFO:captions.json not found.
INFO:corruption.json not found.
INFO:discord.dat not found.
INFO:info.json not found.
INFO:media.json not found.
INFO:prompt.json not found.
INFO:web.json not found.
Exception in thread Thread-4 (listen):
Traceback (most recent call last):
  File "C:\Users\Shez\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Shez\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\src\panic.py", line 33, in listen
    with Listener(address=ADDRESS, authkey=AUTHKEY) as listener:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shez\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 464, in __init__
    self._listener = SocketListener(address, family, backlog)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shez\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\connection.py", line 608, in __init__
    self._socket.bind(address)

then pictures do show up in the command prompt: 
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35742_484e0cd48956ae59431b7c71945fd31f92cfddf7.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35741_72ffaac72eb193ddf2196d99d8fa8c32a66ef239.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35726_4502878716727eb4fda868708a987890751990b3.jpg
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35725_dd1a9aac3f4eb564b0f82394266a6c5d7af3d488.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35711_839252b40c48073a21382b6ea0214cb38d3886d7.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35710_cdd5f1c94e42289458a7ac54791d85d949e25eae.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35709_8e3d581ea4375c826e1eb6dc327339d6e458ca95.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35703_29674184362610407b96655ca251830a963c29c5.jpg
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35698_4ac5211952fab38210ace044ff7a30fec7d5c5fa.jpg
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35682_ea0a214895f8fbee95240b588a732a15a507d940.jpg
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35681_e690af5a3c35bb93fe6ea6c64aac93e78f21d30a.jpg
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35674_3a5c9969fa6303f08023b2bcc7af2ec0afac8b9a.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35672_98ea416b8226827c4ea67ef39878954e7ae573fc.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35669_80c300dfabee60121594427987f95225990a8e18.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35668_6fc30fc128fce02a2051198fdba71462666bd71d.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35664_e6ed2f5f17813010cdabaec0119ae5d5773769c2.png
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35663_74b7da6162da3b97511d0bbc0b42c25342c86e9d.gif
C:\Users\Shez\Desktop\EdgewarePlusPlus-main\edgeware\data\...ensored_35655_fe06cf549c914e6c57f24edb0d6738f904f42f20.jpg

I can confirm that when I go to my "data" and then "download," images are coming in. However, even after all that, nothing pops up on my screen (I have VLC installed), except for the first starter image that then fades away.

what could be my issue here? thanks for reading!

**Comment by shez101** [comment]
btw i do have a resource pack installed and  imported

**Comment by LewdDevelopment** [comment]
Edgeware uses sockets for sending and receiving panic signals in certain cases, it listens on `localhost:6000` and it looks like you may already have something else running on that address. Try changing `6000` in line 10 of `edgeware/src/panic.py` to something else:
```python
ADDRESS = ("localhost", 6000)
```

**Comment by shez101** [comment]
Did that error seem to have gone away, but the same issue is still there. The loading flair appears and then just fades away. When I run through the debug way, I get this while the loading flair pops up and then fades away. I re-downloaded your latest version today and nothing changed. It's the same thing. I read the code and noticed that you removed the lanczos function. Yeah, the description you added was pretty accurate. Even in the other version made by the creator, it did not work when I tried it a couple of months ago. It seems like I'm having the same issue. Also tried disconnecting it from github from the config menu did not do much. Another thing I would like to bring up is whether it is normal for import functions and from functions to be highlighted in yellow, indicating that it "Could not be resolved" in Pylance. Is that supposed to be normal?
![image](https://github.com/user-attachments/assets/0ed1fdcc-e630-40cd-8771-c544bd8a2776)
![image](https://github.com/user-attachments/assets/bfd37acd-d041-4eb7-9db0-3d609dd7468f)

**Comment by LewdDevelopment** [comment]
Since it isn't finding any of the JSON files, have you loaded any pack and are you sure it's in the correct location? Packs should be placed/loaded under `edgeware/resource`.

**Comment by LewdDevelopment** [comment]
I'm going to assume your problem has been fixed. If you still have problems, feel free to ask again!
